version: '3.8'

networks:
  mynetwork:
    driver: bridge

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:test@db:5432/postgres
    depends_on:
      - db
      - redis
    networks:
      - mynetwork

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

  redis:
    container_name: abantether_redis
    image: redis:7.2
    networks:
      - mynetwork
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data

volumes:
  postgres:
  redis-data:
